"""
Django settings for Sky_project project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

# Imports Path so Django can build file paths safely.
from pathlib import Path

# Base directory for the whole Django project.
BASE_DIR = Path(__file__).resolve().parent.parent


# security settings
# Secret key is used by Django for security features such as sessions.
SECRET_KEY = 'django-insecure-p4=w0ld-f=dzp^&nr-+9t_!#8)lo%75kyw@ec5#(9vh#997#hs'

# Debug is true during development so errors are easier to find.
DEBUG = True

# Hosts allowed to run this project.
ALLOWED_HOSTS = []


# installed applications
INSTALLED_APPS = [
    'django.contrib.admin',  # Django admin dashboard
    'django.contrib.auth',  # Django authentication system
    'django.contrib.contenttypes',  # supports Django models and permissions
    'django.contrib.sessions',  # stores user session data
    'django.contrib.messages',  # allows success and error messages
    'django.contrib.staticfiles',  # handles css and static files

    # messages app for inbox, sent, drafts, search and admin models
    'messages.apps.MessagesConfig',

    # accounts app for signup, login, logout and password reset
    'accounts.apps.AccountsConfig',
]


# middleware controls request and response processing
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  # adds security protection
    'django.contrib.sessions.middleware.SessionMiddleware',  # enables sessions
    'django.middleware.common.CommonMiddleware',  # handles common Django features
    'django.middleware.csrf.CsrfViewMiddleware',  # protects forms from csrf attacks
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # connects users to requests
    'django.contrib.messages.middleware.MessageMiddleware',  # enables feedback messages
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # protects against clickjacking
]


# main url configuration file
ROOT_URLCONF = 'Sky_project.urls'


# template settings
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # Allows Django to find the shared templates folder.
        'DIRS': [BASE_DIR / 'templates'],

        # Allows Django to find templates inside each app.
        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',  # allows templates to access request data
                'django.contrib.auth.context_processors.auth',  # allows templates to access user data
                'django.contrib.messages.context_processors.messages',  # allows templates to show messages
            ],
        },
    },
]


# WSGI application used when deploying the project.
WSGI_APPLICATION = 'Sky_project.wsgi.application'


# database configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # uses SQLite database
        'NAME': BASE_DIR / 'db.sqlite3',  # database file location
    }
}


# password validation rules used by Django.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# language and time settings
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# static files such as css
STATIC_URL = 'static/'

# Allows Django to find the static folder.
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

# Redirects users to the login page when a protected page is accessed.
LOGIN_URL = 'login'

# Default id field type for database models.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Sends password reset emails to the terminal during testing.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'